# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: "https://viveks.me"
title: Vivek Srikrishnan
email: viveks@cornell.edu
author: Vivek Srikrishnan
description: > # "Write an awesome description for your new site here.
  Climate, Risk, and Complex Systems @ Cornell BEE
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'
baseurl: ""

# ----------------------- #
#   contact               #
# ----------------------- #

twitter_username:
github: vsrikrish

office: 318 Riley-Robb Hall
department: Biological & Environmental Engineering
city: Ithaca, NY
zip: 14853-5701
labpage: https://viveks.bee.cornell.edu

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   Links                 #
# ----------------------- #

contact:
  - title: Email Me
    url: mailto:viveks@cornell.edu
    iconset: fa
    icon: envelope-o
  - title: Schedule a Meeting
    url: https://calendly.com/vsrikrish
    iconset: fa
    icon: calendar

links:
  - title: Research Group
    url: https://viveks.bee.cornell.edu
    iconset: fa
    icon: home
  - title: Curriculum Vitae
    url: https://viveks.me/assets/pdf/Srikrishnan-CV.pdf
    iconset: ai
    icon: cv
  - title: Google Scholar
    url: https://scholar.google.com/citations?user=CY_JxugAAAAJ
    iconset: ai
    icon: google-scholar
  - title: GitHub
    url: https://github.com/vsrikrish
    iconset: fa
    icon: github
