# Site settings
title: Vivek Srikrishnan
email: vs498@cornell.edu
description: > # this means to ignore newlines until "baseurl:"
  This is the personal website for Vivek Srikrishnan, Assistant Professor, Department of Biological & Environmental Engineering, Cornell University.
baseurl: ""
url: "viveks.me"

twitter_username:
github: vsrikrish

office: 318 Riley-Robb Hall
department: Biological & Environmental Engineering
city: Ithaca, NY
zip: 14853-5701
labpage: https://srikrishnan-lab.github.io

# Build settings
markdown: kramdown
