name: Update CV submodules

on:
  repository_dispatch:
    types: [ push-bib, push-cv-data ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Update cv/bibliography and cv/data submodules
        run: git submodule update --remote cv/bibliography cv/data
      - name: Commit
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add cv/bibliography cv/data
          git diff --staged --quiet || git commit -m "update cv submodules"
      - name: Push
        run: git push
